languageCode: en-us
baseURL: "https://charanravi-online.github.io/"
title: Charan R
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Charan R
  description: "Your friendly neighborhood, tech enthusiast \U0001F44B"
  keywords: [Blog, Portfolio, Data Science]
  author: Charan R
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2023"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Charan R"
    icon: "images/coding.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Charan R"
    subtitle: "Your friendly neighbourhood, tech enthusiast \U0001F44B"
    imageUrl: "images/dp.jpeg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: "Charan R Image"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Charan R \U0001F44B"
    Content: "Your friendly neighborhood, Tech enthusiast \U0001F44B"

  socialIcons:
    
    - name: github
      url: "https://github.com/charanravi-online"
    - name: linkedin
      url: "https://www.linkedin.com/in/r-charan"
    - name: twitter
      url: "https://twitter.com/iambrokendemon"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: music
      name: Music
      url: /music/
      weight: 3
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
